language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk7

sudo: required

dist: trusty

cache:
  directories:
    - $HOME/.ivy2/
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions/
    - $HOME/.sbt/boot/scala-2.10.6/
    - $HOME/.sbt/boot/scala-2.11.8/

env:
  matrix:
    - PIP_BIN=pip PYSPARK_PYTHON=python2 TF_BUILD=tensorflow-0.10.0-cp27-none-linux_x86_64.whl SCALA_BINARY_VERSION="2.11.8" SPARK_VERSION="2.1.0" SPARK_BUILD="spark-2.1.0-bin-hadoop2.7" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz"
    - PIP_BIN=pip PYSPARK_PYTHON=python2 TF_BUILD=tensorflow-0.10.0-cp27-none-linux_x86_64.whl SCALA_BINARY_VERSION="2.10.6" SPARK_VERSION="2.1.0" SPARK_BUILD="spark-2.1.0-bin-hadoop2.7" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz"
    - PIP_BIN=pip3 PYSPARK_PYTHON=python3 TF_BUILD=tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl SCALA_BINARY_VERSION="2.11.8" SPARK_VERSION="2.1.0" SPARK_BUILD="spark-2.1.0-bin-hadoop2.7" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz"
    - PIP_BIN=pip3 PYSPARK_PYTHON=python3 TF_BUILD=tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl SCALA_BINARY_VERSION="2.10.6" SPARK_VERSION="2.1.0" SPARK_BUILD="spark-2.1.0-bin-hadoop2.7" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz"

before_install:
 - ./bin/download_travis_dependencies.sh

install:
 - $PIP_BIN install --user -r ./python/requirements.txt
 - $PIP_BIN install --user --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/$TF_BUILD

script:
 - sbt -Dspark.version=$SPARK_VERSION "set scalaVersion := \"$SCALA_BINARY_VERSION\"" "set test in assembly := {}" assembly
 - sbt -Dspark.version=$SPARK_VERSION -Dpython.version=$PYSPARK_PYTHON "set scalaVersion := \"$SCALA_BINARY_VERSION\"" test
 - SPARK_HOME=$HOME/.cache/spark-versions/$SPARK_BUILD ./python/run-tests.sh

