language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk7

sudo: required

dist: trusty

cache:
  directories:
    - $HOME/.ivy2/
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions/
    - $HOME/.sbt/boot/scala-2.10.4/
    - $HOME/.sbt/boot/scala-2.10.5/
    - $HOME/.sbt/boot/scala-2.10.6/
    - $HOME/.sbt/boot/scala-2.11.8/

env:
  matrix:
    - SCALA_BINARY_VERSION="2.11.8" SPARK_VERSION=2.0.0RC4 SPARK_BUILD="spark-2.0.0-bin-hadoop2.7" SPARK_BUILD_URL="http://people.apache.org/~pwendell/spark-releases/spark-2.0.0-rc4-bin/spark-2.0.0-bin-hadoop2.7.tgz"

before_install:
 - ./bin/download_travis_dependencies.sh

install:
 - pip install --user -r ./python/requirements.txt
 - pip install --user --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl

script:
 - sbt -Dspark.version=$SPARK_VERSION "set scalaVersion := \"$SCALA_BINARY_VERSION\"" "set test in assembly := {}" assembly
 - sbt -Dspark.version=$SPARK_VERSION "set scalaVersion := \"$SCALA_BINARY_VERSION\"" test
 - SPARK_HOME=$HOME/.cache/spark-versions/$SPARK_BUILD ./python/run-tests.sh

